const $=id=>document.getElementById(id);
const form=$('appointment-form'),statusEl=$('status'),listEl=$('appointments');
const googleStatusEl=$('googleStatus'),roleStatusEl=$('roleStatus'),connectGoogleBtn=$('connectGoogle');
const appContent=$('appContent'),lockedNotice=$('lockedNotice'),permissionFieldset=$('permissionFieldset'),brandingPanel=$('brandingPanel'),catalogPanel=$('catalogPanel');
const editingIdEl=$('editingId'),saveAppointmentBtn=$('saveAppointment'),cancelEditBtn=$('cancelEdit');
const availabilityInline=$('availabilityInline'),slotsEl=$('slots');
let currentUser=null,currentRole='customer',availabilityTimer=null,services=[],professionals=[];

const fields={clientName:$('clientName'),clientPhone:$('clientPhone'),clientEmail:$('clientEmail'),professionalId:$('professionalId'),serviceId:$('serviceId'),startsAt:$('startsAt'),durationMinutes:$('durationMinutes'),allowEdit:$('allowEdit'),allowDelete:$('allowDelete'),allowReschedule:$('allowReschedule'),rescheduleLimitHours:$('rescheduleLimitHours'),reminderEmail:$('reminderEmail'),reminderWhatsapp:$('reminderWhatsapp'),reminderBrowser:$('reminderBrowser'),reminderMinutes:$('reminderMinutes')};
const requiredFields=[['clientName','Cliente'],['clientPhone','WhatsApp'],['serviceId','Serviço'],['startsAt','Data e hora'],['durationMinutes','Duração'],['reminderMinutes','Minutos antes']];

function escapeHtml(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function toDatetimeLocal(iso){const d=new Date(iso);if(Number.isNaN(d.getTime()))return'';return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function normalize(a){return{id:a.id,clientName:a.client_name??a.clientName,clientPhone:a.client_phone??a.clientPhone,clientEmail:a.client_email??a.clientEmail,professionalId:a.professional_id??a.professionalId,serviceId:a.service_id??a.serviceId,serviceName:a.service_name??a.serviceName,startsAt:a.starts_at??a.startsAt,durationMinutes:Number(a.duration_minutes??a.durationMinutes??60),allowReschedule:a.allow_reschedule??a.allowReschedule??true,rescheduleLimitHours:Number(a.reschedule_limit_hours??a.rescheduleLimitHours??6),permissions:a.permissions||{},reminders:a.reminders||{},status:a.status||'scheduled'};}
async function googleToken(){const r=await browser.runtime.sendMessage({type:'BGD_GOOGLE_TOKEN'});return r?.accessToken||null;}
async function api(action,payload={}){const token=await googleToken();if(!token)throw new Error('google_login_required');const r=await fetch(BGD_CONFIG.BACKEND_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':BGD_CONFIG.SUPABASE_PUBLISHABLE_KEY,'x-google-access-token':token},body:JSON.stringify({action,...payload})});const data=await r.json().catch(()=>({}));if(!r.ok||data.ok===false){const e=new Error(data.error||`http_${r.status}`);e.status=r.status;e.data=data;throw e;}return data;}

function applyBranding(b){if(!b)return;document.documentElement.style.setProperty('--bgd-primary',b.primary_color||'#111827');document.documentElement.style.setProperty('--bgd-bg',b.background_color||'#f5f7fa');document.documentElement.style.setProperty('--bgd-radius',`${Number(b.button_radius??8)}px`);document.documentElement.style.setProperty('--bgd-font',b.font_family||'system-ui');$('brandName').textContent=b.business_name||'BrasilGuard Agenda';$('brandWelcome').textContent=b.welcome_message||'';if(b.logo_url){$('brandLogo').src=b.logo_url;$('brandLogo').hidden=false;}else $('brandLogo').hidden=true;}
async function loadBranding(){try{const r=await api('branding_get');applyBranding(r.branding);fillBrandingForm(r.branding);}catch(_e){}}
function fillBrandingForm(b={}){$('brandingBusinessName').value=b.business_name||'BrasilGuard Agenda';$('brandingLogoUrl').value=b.logo_url||'';$('brandingCoverUrl').value=b.cover_url||'';$('brandingPrimary').value=b.primary_color||'#111827';$('brandingSecondary').value=b.secondary_color||'#f3f4f6';$('brandingBackground').value=b.background_color||'#f5f7fa';$('brandingRadius').value=Number(b.button_radius??8);$('brandingButtonStyle').value=b.button_style||'solid';$('brandingWelcome').value=b.welcome_message||'';}

async function loadCatalogs(){const [pr,sr]=await Promise.all([api('professionals'),api('services')]);professionals=pr.professionals||[];services=sr.services||[];fillSelects();}
function fillSelects(){const pOpts=professionals.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}${p.specialty?` — ${escapeHtml(p.specialty)}`:''}</option>`).join('');$('professionalId').innerHTML='<option value="">Sem profissional específico</option>'+pOpts;$('availabilityProfessional').innerHTML='<option value="">Todos / não definido</option>'+pOpts;$('catalogAssignmentProfessional').innerHTML='<option value="">Selecione</option>'+pOpts;const sOpts=services.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('');$('serviceId').innerHTML='<option value="">Selecione</option>'+sOpts;$('catalogAssignmentService').innerHTML='<option value="">Selecione</option>'+sOpts;}
async function loadServicesForProfessional(){const pid=fields.professionalId.value;if(!pid){fillSelects();return;}const r=await api('professional_services',{professionalId:pid});const rows=r.services||[];fields.serviceId.innerHTML='<option value="">Selecione</option>'+rows.map(x=>`<option value="${x.service_id}" data-duration="${x.duration_minutes}">${escapeHtml(x.bgd_agenda_services?.name||'Serviço')}</option>`).join('');}
fields.professionalId.addEventListener('change',async()=>{await loadServicesForProfessional();checkAvailability();});
fields.serviceId.addEventListener('change',()=>{const o=fields.serviceId.selectedOptions[0];if(o?.dataset?.duration)fields.durationMinutes.value=o.dataset.duration;else{const s=services.find(x=>x.id===fields.serviceId.value);if(s)fields.durationMinutes.value=s.duration_minutes;}checkAvailability();});

async function initializeIdentity(){const s=await browser.runtime.sendMessage({type:'BGD_GOOGLE_STATUS'});if(!s?.connected){googleStatusEl.textContent='Não conectado.';appContent.hidden=true;lockedNotice.hidden=false;return;}try{const who=await api('whoami');currentUser=who.user;currentRole=who.user.role||'customer';googleStatusEl.textContent=`Conectado: ${who.user.email}`;roleStatusEl.textContent=`Perfil: ${currentRole}`;connectGoogleBtn.textContent='Reconectar Google';appContent.hidden=false;lockedNotice.hidden=true;fields.clientEmail.value=who.user.email||'';if(!fields.clientName.value)fields.clientName.value=who.user.name||'';permissionFieldset.hidden=currentRole!=='admin';brandingPanel.hidden=currentRole!=='admin';catalogPanel.hidden=!['operator','manager','admin'].includes(currentRole);$('appointmentsTitle').textContent=currentRole==='customer'?'Meus agendamentos':'Agenda completa';await Promise.all([loadBranding(),loadCatalogs()]);await loadAppointments();}catch(e){googleStatusEl.textContent=`Falha de autorização: ${e.message}`;appContent.hidden=true;lockedNotice.hidden=false;}}
connectGoogleBtn.addEventListener('click',async()=>{connectGoogleBtn.disabled=true;googleStatusEl.textContent='Abrindo autorização do Google...';const r=await browser.runtime.sendMessage({type:'BGD_GOOGLE_CONNECT'});connectGoogleBtn.disabled=false;if(!r?.ok){googleStatusEl.textContent=`Falha: ${r?.error||'erro desconhecido'}`;return;}await initializeIdentity();});

async function checkAvailability(){if(!fields.startsAt.value||!fields.durationMinutes.value)return;availabilityInline.textContent='Verificando disponibilidade...';try{const r=await api('availability',{startsAt:new Date(fields.startsAt.value).toISOString(),durationMinutes:Number(fields.durationMinutes.value),excludeId:editingIdEl.value||null,professionalId:fields.professionalId.value||null});availabilityInline.textContent=r.available?'Horário disponível ✅':`Horário indisponível ❌ (${r.reason||'conflito'})`;availabilityInline.className=`availability-inline ${r.available?'ok':'bad'}`;return r.available;}catch(e){availabilityInline.textContent=`Não foi possível verificar: ${e.message}`;availabilityInline.className='availability-inline bad';return false;}}
for(const el of [fields.startsAt,fields.durationMinutes])el.addEventListener('input',()=>{clearTimeout(availabilityTimer);availabilityTimer=setTimeout(checkAvailability,250);});
$('checkSlots').addEventListener('click',async()=>{slotsEl.textContent='Consultando agenda...';try{const r=await api('slots',{date:$('availabilityDate').value,durationMinutes:Number($('availabilityDuration').value||60),professionalId:$('availabilityProfessional').value||null});slotsEl.innerHTML='';if(!r.slots?.length){slotsEl.textContent='Sem expediente nesta data.';return;}for(const slot of r.slots){const b=document.createElement('button');b.type='button';b.className=`slot ${slot.status==='free'?'free':'busy'}`;b.innerHTML=`<span>${new Date(slot.startsAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span><strong>${slot.status==='free'?'LIVRE':'OCUPADO'}</strong>`;if(slot.status==='free'){b.addEventListener('click',()=>{fields.startsAt.value=toDatetimeLocal(slot.startsAt);fields.durationMinutes.value=$('availabilityDuration').value||60;fields.professionalId.value=$('availabilityProfessional').value||'';checkAvailability();window.scrollTo({top:form.offsetTop-20,behavior:'smooth'});});}else b.disabled=true;slotsEl.appendChild(b);}}catch(e){slotsEl.textContent=`Falha ao consultar agenda: ${e.message}`;}});

function permissionsOf(a){return{edit:a.permissions?.edit!==false,delete:a.permissions?.delete!==false,reschedule:a.permissions?.reschedule!==false&&a.allowReschedule!==false};}
async function loadAppointments(){try{const r=await api(currentRole==='customer'?'list_mine':'list_all');const items=(r.appointments||[]).map(normalize).filter(a=>a.status!=='cancelled');renderAppointments(items);}catch(e){listEl.textContent=`Falha ao carregar agenda: ${e.message}`;}}
function renderAppointments(items){listEl.innerHTML=items.length?'':'<small>Nenhum agendamento.</small>';for(const a of items){const p=permissionsOf(a),elevated=currentRole!=='customer';const prof=professionals.find(x=>x.id===a.professionalId)?.name||'Sem profissional';const div=document.createElement('div');div.className='appointment';div.innerHTML=`<strong>${escapeHtml(a.clientName||'')}</strong>${escapeHtml(a.serviceName||'')} · ${escapeHtml(prof)}<br>${new Date(a.startsAt).toLocaleString('pt-BR')} · ${a.durationMinutes} min<div class="permissions">Reagendamento: ${p.reschedule?'permitido':'bloqueado'} · Cancelamento: ${p.delete?'permitido':'bloqueado'}</div><div class="appointment-actions"></div>`;const actions=div.querySelector('.appointment-actions');if(elevated||p.edit){const b=document.createElement('button');b.type='button';b.textContent='Editar';b.addEventListener('click',()=>startEdit(a));actions.appendChild(b);}if(elevated||p.delete){const b=document.createElement('button');b.type='button';b.className='danger';b.textContent='Cancelar';b.addEventListener('click',()=>cancelAppointment(a));actions.appendChild(b);}listEl.appendChild(div);}}
$('reloadAppointments').addEventListener('click',loadAppointments);

async function startEdit(a){editingIdEl.value=a.id;fields.clientName.value=a.clientName||'';fields.clientPhone.value=a.clientPhone||'';fields.clientEmail.value=a.clientEmail||currentUser?.email||'';fields.professionalId.value=a.professionalId||'';await loadServicesForProfessional();fields.serviceId.value=a.serviceId||'';fields.startsAt.value=toDatetimeLocal(a.startsAt);fields.durationMinutes.value=a.durationMinutes||60;fields.allowEdit.checked=a.permissions?.edit!==false;fields.allowDelete.checked=a.permissions?.delete!==false;fields.allowReschedule.checked=a.allowReschedule!==false;fields.rescheduleLimitHours.value=a.rescheduleLimitHours||6;fields.reminderEmail.checked=Boolean(a.reminders?.email);fields.reminderWhatsapp.checked=Boolean(a.reminders?.whatsapp);fields.reminderBrowser.checked=Boolean(a.reminders?.browser);fields.reminderMinutes.value=Number(a.reminders?.minutesBefore||60);saveAppointmentBtn.textContent='Salvar alterações';cancelEditBtn.hidden=false;statusEl.textContent='Editando agendamento.';checkAvailability();window.scrollTo({top:0,behavior:'smooth'});}
function resetForm(){editingIdEl.value='';form.reset();fields.clientEmail.value=currentUser?.email||'';fields.clientName.value=currentUser?.name||'';fields.allowEdit.checked=fields.allowDelete.checked=fields.allowReschedule.checked=true;fields.reminderEmail.checked=fields.reminderWhatsapp.checked=fields.reminderBrowser.checked=true;fields.durationMinutes.value=60;fields.rescheduleLimitHours.value=6;fields.reminderMinutes.value=60;saveAppointmentBtn.textContent='Salvar agendamento';cancelEditBtn.hidden=true;fillSelects();availabilityInline.textContent='Escolha profissional, serviço, data e hora para verificar disponibilidade.';availabilityInline.className='availability-inline';}
cancelEditBtn.addEventListener('click',()=>{resetForm();statusEl.textContent='Edição cancelada.';});
async function cancelAppointment(a){if(!confirm(`Cancelar o agendamento de ${a.clientName}?`))return;try{await api('cancel',{id:a.id,reason:'Cancelado pelo usuário'});await browser.runtime.sendMessage({type:'BGD_APPOINTMENT_DELETED',appointment:a});statusEl.textContent='Agendamento cancelado. Mensagem transacional enfileirada.';await loadAppointments();}catch(e){statusEl.textContent=`Não foi possível cancelar: ${e.message}`;}}
function validateRequired(){const missing=[];for(const [key,label] of requiredFields){const el=fields[key],raw=String(el.value??'').trim();if(!raw||(el.type==='number'&&Number(raw)<Number(el.min||0))){missing.push(label);el.classList.add('field-error');}else el.classList.remove('field-error');}if(missing.length){statusEl.textContent=`Preencha: ${missing.join(', ')}.`;return false;}return true;}
form.addEventListener('submit',async e=>{e.preventDefault();if(!currentUser){statusEl.textContent='Entre com Google antes de agendar.';return;}if(!validateRequired())return;const available=await checkAvailability();if(!available){statusEl.textContent='Não foi salvo: o intervalo escolhido não está disponível.';return;}const service=services.find(x=>x.id===fields.serviceId.value);const selectedText=fields.serviceId.selectedOptions[0]?.textContent||service?.name||'';const a={id:editingIdEl.value||crypto.randomUUID(),clientName:fields.clientName.value.trim(),clientPhone:fields.clientPhone.value.trim(),clientEmail:fields.clientEmail.value.trim(),professionalId:fields.professionalId.value||null,serviceId:fields.serviceId.value||null,serviceName:selectedText,startsAt:new Date(fields.startsAt.value).toISOString(),durationMinutes:Number(fields.durationMinutes.value),allowReschedule:fields.allowReschedule.checked,rescheduleLimitHours:Number(fields.rescheduleLimitHours.value||0),permissions:{edit:fields.allowEdit.checked,delete:fields.allowDelete.checked,reschedule:fields.allowReschedule.checked},reminders:{email:fields.reminderEmail.checked,whatsapp:fields.reminderWhatsapp.checked,browser:fields.reminderBrowser.checked,minutesBefore:Number(fields.reminderMinutes.value)}};try{if(editingIdEl.value){const r=await api('update',{id:a.id,appointment:a});const saved=normalize(r.appointment);await browser.runtime.sendMessage({type:'BGD_APPOINTMENT_UPDATED',appointment:saved});statusEl.textContent='Agendamento atualizado.';}else{const r=await api('create',{appointment:a});const saved=normalize(r.appointment);await browser.runtime.sendMessage({type:'BGD_APPOINTMENT_CREATED',appointment:saved});statusEl.textContent='Agendamento confirmado. Mensagens transacionais enfileiradas.';}resetForm();await loadAppointments();}catch(err){statusEl.textContent=err.data?.error==='slot_unavailable'?'Horário acabou de ficar indisponível. Escolha outro horário.':`Falha ao salvar: ${err.message}`;}});

$('clientCatalogForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('client_upsert',{client:{name:$('catalogClientName').value.trim(),phone:$('catalogClientPhone').value.trim(),email:$('catalogClientEmail').value.trim(),document:$('catalogClientDocument').value.trim(),birthDate:$('catalogClientBirth').value||null,notes:$('catalogClientNotes').value.trim()}});e.target.reset();statusEl.textContent='Cliente avulso salvo.';}catch(err){statusEl.textContent=`Falha ao salvar cliente: ${err.message}`;}});
$('professionalCatalogForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('professional_upsert',{professional:{name:$('catalogProfessionalName').value.trim(),specialty:$('catalogProfessionalSpecialty').value.trim(),phone:$('catalogProfessionalPhone').value.trim(),email:$('catalogProfessionalEmail').value.trim(),photoUrl:$('catalogProfessionalPhoto').value.trim()}});e.target.reset();await loadCatalogs();statusEl.textContent='Profissional salvo.';}catch(err){statusEl.textContent=`Falha ao salvar profissional: ${err.message}`;}});
$('serviceCatalogForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('service_upsert',{service:{name:$('catalogServiceName').value.trim(),durationMinutes:Number($('catalogServiceDuration').value),bufferBeforeMinutes:Number($('catalogServiceBefore').value||0),bufferAfterMinutes:Number($('catalogServiceAfter').value||0)}});e.target.reset();$('catalogServiceDuration').value=60;$('catalogServiceBefore').value=0;$('catalogServiceAfter').value=0;await loadCatalogs();statusEl.textContent='Serviço salvo.';}catch(err){statusEl.textContent=`Falha ao salvar serviço: ${err.message}`;}});
$('assignmentCatalogForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('professional_service_upsert',{assignment:{professionalId:$('catalogAssignmentProfessional').value,serviceId:$('catalogAssignmentService').value,durationMinutes:Number($('catalogAssignmentDuration').value),price:$('catalogAssignmentPrice').value,bufferBeforeMinutes:Number($('catalogAssignmentBefore').value||0),bufferAfterMinutes:Number($('catalogAssignmentAfter').value||0),onlineBookingEnabled:$('catalogAssignmentOnline').checked}});statusEl.textContent='Serviço vinculado ao profissional.';}catch(err){statusEl.textContent=`Falha ao vincular serviço: ${err.message}`;}});

$('saveBranding').addEventListener('click',async()=>{const branding={business_name:$('brandingBusinessName').value.trim(),logo_url:$('brandingLogoUrl').value.trim()||null,cover_url:$('brandingCoverUrl').value.trim()||null,primary_color:$('brandingPrimary').value,secondary_color:$('brandingSecondary').value,background_color:$('brandingBackground').value,button_radius:Number($('brandingRadius').value||8),button_style:$('brandingButtonStyle').value,welcome_message:$('brandingWelcome').value.trim()};try{const r=await api('branding_update',{branding});applyBranding(r.branding);statusEl.textContent='Tema atualizado.';}catch(e){statusEl.textContent=`Falha ao salvar tema: ${e.message}`;}});

(async()=>{const today=new Date();$('availabilityDate').value=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);await initializeIdentity();})();